<div class="footer_top">
	<div class="row">
		<div class="footer_top_i">
			<div class="footer_top_i_l">
				<h2>
					<a href="/"><img src="./common/images/logo_ft.png" alt="logo"></a>
				</h2>
				<p>〒540-0008<br>大阪市中央区大手前1丁目7番31号 OMMビル18階<br>TEL：<a href="tel:0120144059"></a>0120-14-4059（代表：06-6966-8877）</p>
				<div class="btn_ft">
					<a href="#">事務所紹介</a>
				</div>
			</div>
			<div class="footer_top_i_r">
				<ul>
					<li><a href="#">HOME</a></li>
					<li><a href="#">会社設立基礎知識</a></li>
					<li><a href="#">料金表</a></li>
					<li><a href="#">事務所案内</a></li>
					<li><a href="#">ご相談のながれ</a></li>
					<li><a href="#">大阪会社設立ネットの思い</a></li>
				</ul>
				<ul>
					<li><a href="#">会社設立後のサポート</a></li>
					<li><a href="#">執筆実績</a></li>
					<li><a href="#">業種別会社設立</a></li>
					<li><a href="#">ＮＰＯ法人の会社設立</a></li>
					<li><a href="#">採用情報</a></li>
					<li><a href="#">お問い合わせ</a></li>
				</ul>
			</div>
		</div>
	</div>
</div>
<a href="#" class="top show_pc" id="pagetop"><img src="./common/images/top.png" alt=""></a>
<p class="copyright">Copyright &copy; 2011 大阪会社設立ネットAll Rights Reserved.</p>
