<div class="hd_top">
  <a class="hd_logo" href="/"><img src="./common/images/logo.png" alt="Logo"></a>
  <!--/.logo-->
  <nav class="nav" id="nav">
    <ul>
      <li><a href="/">HOME</a></li>
      <li class="has_child">
        <a href="#">料金表</a>
        <span class="sub show_pc"></span>
      </li>
      <li class="has_child">
        <a href="#">事務所案内</a>
        <span class="sub show_pc"></span>
      </li>
      <li><a href="#">ご相談の流れ</a></li>
      <li><a href="#">大阪会社設立ネットの思い</a></li>
      <li><a class="btn" href="#">お問い合わせ</a></li>
    </ul>
  </nav>
  <!--/.nav-->
  <div class="menu show_sp" id="icon_nav">
    <div class="icon_menu">
      <div class="icon_inner"></div>
    </div>
  </div>
  <!--/.icon_nav-->
</div>
